theme = "nord_light"

[editor]
line-number = "relative"
mouse = false
completion-replace = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

